- name: Load environment variables
  hosts: localhost
  tasks:
    - name: Load vars from file
      include_vars:
        file: vm_config.yml
        name: vm_config

    - name: Debug environment variables
      debug:
        var: vm_config

- name: Proxmox VM setup and configuration
  hosts: pve
  gather_facts: no
  vars:
    proxmox_api_url: "{{ hostvars['localhost']['vm_config']['PROXMOX_API_URL'] }}"
    proxmox_user: "{{ hostvars['localhost']['vm_config']['PROXMOX_USER'] }}"
    proxmox_password: "{{ hostvars['localhost']['vm_config']['PROXMOX_PASSWORD'] }}"
    template_vmid: "{{ hostvars['localhost']['vm_config']['TEMPLATE_VMID'] }}"
    default_ip: "{{ hostvars['localhost']['vm_config']['DEFAULT_IP'] }}"
    node_vms:
      - vmid: "{{ hostvars['localhost']['vm_config']['VM_1_VMID'] }}"
        name: "{{ hostvars['localhost']['vm_config']['VM_1_NAME'] }}"
        ip: "{{ hostvars['localhost']['vm_config']['VM_1_IP'] }}"
      - vmid: "{{ hostvars['localhost']['vm_config']['VM_2_VMID'] }}"
        name: "{{ hostvars['localhost']['vm_config']['VM_2_NAME'] }}"
        ip: "{{ hostvars['localhost']['vm_config']['VM_2_IP'] }}"
      - vmid: "{{ hostvars['localhost']['vm_config']['VM_3_VMID'] }}"
        name: "{{ hostvars['localhost']['vm_config']['VM_3_NAME'] }}"
        ip: "{{ hostvars['localhost']['vm_config']['VM_3_IP'] }}"
      - vmid: "{{ hostvars['localhost']['vm_config']['VM_4_VMID'] }}"
        name: "{{ hostvars['localhost']['vm_config']['VM_4_NAME'] }}"
        ip: "{{ hostvars['localhost']['vm_config']['VM_4_IP'] }}"

  tasks:
    - name: Clone all VMs from template
      command: >
        qm clone {{ template_vmid }} {{ item.vmid }} --full --name {{ item.name }} --storage local-lvm
      loop: "{{ node_vms }}"
      delegate_to: pve

    - name: Start and configure VMs one by one
      include_tasks: configure_vm.yml
      loop: "{{ node_vms }}"
      loop_control:
        loop_var: node